name: Mosquée Thonon front ReactJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install

    - name: Set API URL
      run: |        
        if [ "${{ github.event.repository.env }}" = "PRODUCTION" ]; then
          echo "BUILD_ENV=build" >> $GITHUB_ENV
        else
          echo "BUILD_ENV=build:staging" >> $GITHUB_ENV
        fi
        
    - name: Build React app
      run: npm run ${{ env.BUILD_ENV }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mosqueethononfront
        path: build

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'  # Déclenchement de ce job manuellement

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: mosqueethononfront

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Update ReactJS App
      run: scp -r -o StrictHostKeyChecking=no * ubuntu@${{ secrets.TARGET_SERVER_IP }}:/var/www/mosquee-thonon/
