name: Mosquée Thonon front ReactJS

on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
    branches:
      - master
      - 'release-*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement (staging | production)'
        required: true
        default: 'staging'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }} # branche sur laquelle on a déclenché le workflow
          
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install

    - name: Setup Environment properties
      run: |
        if [ "${{ github.event.inputs.environment }}" == "production" ]; then
          echo "${{ vars.ENV_FILE_PRODUCTION }}" > .env
        else
          echo "${{ vars.ENV_FILE_STAGING }}" > .env
        fi
      
    - name: Build React app
      run: npm run build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mosqueethononfront
        path: build

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'  # Déclenchement de ce job manuellement

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: mosqueethononfront

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Update ReactJS App
      run: scp -r -o StrictHostKeyChecking=no * ubuntu@${{ secrets.TARGET_SERVER_IP }}:/var/www/mosquee-thonon/${{ github.event.inputs.environment }}
