on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Branche de release (préciser uniquement la version majeure)'
        required: true

permissions:
  contents: write

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create release branch
        run: |
          git config --global user.name "Aymen"
          git config --global user.email "aymen330d@hotmail.fr"
          RELEASE_VERSION="${{ github.event.inputs.release_version }}.0.0"
          RELEASE_BRANCHE="release-$RELEASE_VERSION"
          git checkout -b $RELEASE_BRANCHE
          npm version $RELEASE_VERSION --no-git-tag-version
          git add package.json
          git commit -m "release branche created ==> $RELEASE_VERSION"
          git push origin $RELEASE_BRANCHE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
