on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Branche de release (préciser uniquement la version majeure)'
        required: true

permissions:
  contents: write

env:
  RELEASE_VERSION: "${{ github.event.inputs.release_version }}.0.0"
  RELEASE_BRANCHE: "release-${{ github.event.inputs.release_version }}.0.0"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Release
        run: |
          git config --global user.name "Aymen"
          git config --global user.email "aymen330d@hotmail.fr"
          CURRENT_BRANCH=${GITHUB_REF_NAME}     
          npm version minor
          git push origin $CURRENT_BRANCH
          git push origin --tags